name: .NET Build and Pack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./src
    - name: Run unit tests
      run: dotnet test --configuration Release
      working-directory: ./src
    - name: Generate nuget package
      run: dotnet pack --configuration Release -o nupkg
      working-directory: ./src
